<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5C1AT4W\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5C1AT4W/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5C1AT4W.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5C1AT4W\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5C1AT4W\App_KernelDevDebugContainer([
    'container.build_hash' => '5C1AT4W',
    'container.build_id' => 'ce6a4412',
    'container.build_time' => 1655142474,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5C1AT4W');
